defaults:
  - model: resnet18
  - data: chest_xray
  - training: base
  - optimizer: adam
  - criterion: ce

experiment_name: ${model.name}_${criterion.name}

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${experiment_name}
